[toolchain]
anchor_version = "0.30"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
junk-pusher-game = "11111111111111111111111111111111"

[programs.gorbagana]
junk-pusher-game = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[scripts]
build = "cargo build"
test = "cargo test"
