[package]
name = "junk-pusher-game"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anchor-lang = "0.30"
solana-program = "1.18"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
